# Generated by Django 5.0.14 on 2026-04-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_category_options_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Uzmanlık Alanı'),
        ),
    ]
