# Generated by Django 5.0.14 on 2026-04-27 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_coupon_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Kullananlar'),
        ),
    ]
