# Generated by Django 5.0.14 on 2026-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_assignment_quiz_quizattempt_quizquestion_quizchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
