# Generated by Django 5.0.14 on 2026-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_systemlog_details_systemlog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
