# Generated by Django 5.0.14 on 2026-05-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0013_lessonprogress_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='new_category_request',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yeni Kategori Talebi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='lms_app.category'),
        ),
    ]
